@startuml SequenceDiagram
participant Подача_заявки_на_грант as Foo
actor       Соискатели    as Foo1
actor       Фонд    as Foo6
actor       Эксперт    as Foo7
participant    Подача_заявки    as Foo2
participant    Оценка_заявки     as Foo3
participant    Результаты_экспертизы      as Foo4
participant    Выдача_гранта   as Foo5

Foo1 -> Foo6 : Выбор фонда
Foo1 -> Foo2 : Сбор документов и подача заявки
Foo2 -> Foo3 : На экспертизу
Foo6 -> Foo5 : Принятие решения о финансировании
Foo4 -> Foo6 : Ознакомление с результатами экспертизы
Foo7 -> Foo3 : Проведение экспертизы
Foo7 -> Foo4 : Итоги экспертизы
Foo5 -> Foo1 : Выдача_гранта
@enduml


@startuml DeploymentDiagram
actor Фонд
node ПК_фонд
node ПК_соискательгранта
node ПК_эксперт


database ИС
Фонд -- ПК_фонд: Вход на платформу
Эксперт -- ПК_эксперт: Вход на платформу
ПК_фонд -- ИС: Открыть прием заявок на получение гранта
ПК_фонд -- ПК_эксперт: Запрос/передача контактов
ПК_эксперт -- ИС: Проведение экспертизы полученной заявки
ПК_эксперт -- ПК_фонд: Передача результатов экспертизы

ПК_соискательгранта -- ИС: Просмотр и выбор фонда
ПК_соискательгранта -- ПК_фонд: Подача заявки
Соискательгранта -- ПК_соискательгранта: Вход на платформу

@enduml